### ISSUE TITLE
Authentication error. {“errors”:[{“code”:32,”message”:”Could not authenticate you.”}]} 

### ISSUE THREAD

**Issue by NarayanasamyP** [robertodoering/twitter_api#11]
Hi Team,

Couldn't get authorized, Always got {"errors":[{"code":32,"message":"Could not authenticate you."}]}

I have gone through the related forums and articles and ensured all those stuffs. Also, the header is generated with all the required parameters. But can't get authorization success response.

Here is my header request for your reference:

1. Header details obtained in PostMan

![image|690x105](https://aws1.discourse-cdn.com/twitter/original/3X/3/8/384123a1e7f56b501c56560d5130169cd47e50b1.png) 

2. Same was got in my flutter application.

![image|690x259](https://aws1.discourse-cdn.com/twitter/optimized/3X/0/6/063bad1eab6fb1704973992ef1501e28e653a5e4_2_690x259.png) 

Note: If **I use Bearer key** to authenticate **it is working fine**. but If i use access keys and access tokens to authenticate I'm getting the authentication error.

Please let me know is there any known issues with Twitter API versions and OAuth version compatibility?

I have done all the below things,

1. Ensured app read & write permission.
2. Regenerated keys and ensured.
3. Ensured trailing white spaces in access keys.
4. Created new app and tried by generating new twitter api keys.
5. Have set some time delay to the twitter client authentication process and got the same authorization issue.

I believe anyone can know the cause for the issue.

Thanks in advance!
- Naren

**Comment by robertodoering** [comment]
Hey Naren,

After looking at the screenshot, it seems that the `oauth_consumer_key` is starting with a quotation mark `"` which gets percent-encoded (`%22`).

Can you verify that your `consumerKey` and `consumerSecret` that you use in the `TwitterClient` are correct?

![image](https://user-images.githubusercontent.com/20045287/116102547-195dd700-a6af-11eb-9a70-125f17850f02.png)
(keys are invalid and just an example, but should look similar)

**Comment by NarayanasamyP** [comment]
Hi Roberto,

Thank you so much for the response.

Yes, I didn't noticed that in the flutter request header screenshot(which I have attached). Yeah, I totally agreed the percentage **%** symbol may cause the issue. 

**I have checked code again and found cause. Resolved it now. Thanks again for the help.**

The reason for I believe that the PostMan web plugin. It also, given the same error. 
![image](https://user-images.githubusercontent.com/34939696/116113206-eb3fbd80-a6d5-11eb-91a5-702ffabb9479.png)

The above may be issue in postman plugin.

Since the issue is resolved by mapping the proper access keys. So, I have closed this issue report.

Regards,
Naren.

**Comment by robertodoering** [comment]
Nice, I'm glad it works now :)

**Comment by rrawann** [comment]
> Nice, I'm glad it works now :)



> Hi Team,
> 
> Couldn't get authorized, Always got {"errors":[{"code":32,"message":"Could not authenticate you."}]}
> 
> I have gone through the related forums and articles and ensured all those stuffs. Also, the header is generated with all the required parameters. But can't get authorization success response.
> 
> Here is my header request for your reference:
> 
>     1. Header details obtained in PostMan
> 
> 
> ![image|690x105](https://camo.githubusercontent.com/576ca70cab3b5121b5d824875e60aa087e651e7675ecddee823cc3936173f3e1/68747470733a2f2f617773312e646973636f757273652d63646e2e636f6d2f747769747465722f6f726967696e616c2f33582f332f382f333834313233613165376635366235303163353635363064353133303136396364343765353062312e706e67)
> 
>     2. Same was got in my flutter application.
> 
> 
> ![image|690x259](https://camo.githubusercontent.com/938da042de5274fc0921be1332c63533ec331d12cb5986bae386dec82a296691/68747470733a2f2f617773312e646973636f757273652d63646e2e636f6d2f747769747465722f6f7074696d697a65642f33582f302f362f303633626164316561623666623137303439373339393265663135303165323865363533613565345f325f363930783235392e706e67)
> 
> Note: If **I use Bearer key** to authenticate **it is working fine**. but If i use access keys and access tokens to authenticate I'm getting the authentication error.
> 
> Please let me know is there any known issues with Twitter API versions and OAuth version compatibility?
> 
> I have done all the below things,
> 
>     1. Ensured app read & write permission.
> 
>     2. Regenerated keys and ensured.
> 
>     3. Ensured trailing white spaces in access keys.
> 
>     4. Created new app and tried by generating new twitter api keys.
> 
>     5. Have set some time delay to the twitter client authentication process and got the same authorization issue.
> 
> 
> I believe anyone can know the cause for the issue.
> 
> Thanks in advance!
> 
>     * Naren

I got the same error Internal Server 500 "message":"Could not authenticate you." ,how can fix it?
