### ISSUE TITLE
Not Working for flutter web

### ISSUE THREAD

**Issue by prashantlamba1** [robertodoering/twitter_api#12]
Access to XMLHttpRequest at 'https://api.twitter.com/1.1/search/tweets.json?q=verified%2BHyderabad%2B%28bed%2BOR%2Bbeds%2BOR%2Bicu%2BOR%2Boxygen%2BOR%2Bventilator%2BOR%2Bventilators%2BOR%2B%2B%2B%2B%2B%2B%2B%2B%29%2B%2520-not%2520verified%2520-unverified%2520-needed%2520-need%2520-needs%2520-required%2520-require%2520-requires%2520-requirement%2520-requirements&locale=en&result_type=recent&count=10&tweet_mode=extended' from origin 'https://govid.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
![image](https://user-images.githubusercontent.com/67849881/118633670-566d4300-b7ef-11eb-9541-53f6c60ce230.png)

**Comment by robertodoering** [comment]
The current twitter API doesn't support CORS, so you won't be able to access it through a browser.

Some info:
https://twittercommunity.com/t/will-twitter-api-support-cors-headers-soon/28276/5
https://stackoverflow.com/questions/35879943/twitter-api-authorization-fails-cors-preflight-in-browser/35898961#35898961
