### ISSUE TITLE
Any plans for Twitter API v2 support?

### ISSUE THREAD

**Issue by MarkOSullivan94** [robertodoering/twitter_api#13]
Just wondering if there's plans for Twitter API V2 support to be added?

https://developer.twitter.com/en/docs/twitter-api/early-access

**Comment by robertodoering** [comment]
I don't plan to add support for the v2 endpoints in this package.
The biggest reason is that the data objects are not interchangeable, so we would need a `Tweet` object for the v1 and a `Tweet` object for the v2.

I can imagine to write a separate package for the new endpoints if a good one doesn't exist once I want to use the api.
