### ISSUE TITLE
Error Instance of 'Response'

### ISSUE THREAD

**Issue by suhardiyan** [robertodoering/twitter_api#14]
Hi, when I try your documentation about uploading image, it comes to error like this :

![image](https://user-images.githubusercontent.com/17775380/134631332-8f74374d-984b-482c-b96c-12ea8025e87d.png)

How can I fix this ? thankyou

**Comment by suhardiyan** [comment]
When I debug your code, resulting {"errors":[{"code":89,"message":"Invalid or expired token."}]}
but if I try using postman, its works

![image](https://user-images.githubusercontent.com/17775380/134637580-b95cd69a-1b4b-456e-b7b4-39d9b73af173.png)

**Comment by suhardiyan** [comment]
wow its my fault, im sorry i forgot to check token

But, you can give us better error handling message instead of `Instance of 'Response'`

**Comment by robertodoering** [comment]
All errors returned by twitter will be a response. The message is not parsed by this package at the moment.
Here is a comment from the example:
```dart
// Requests made by the client can throw the following errors:
//
// * `TimeoutException` when a request hasn't returned a response for some
//   time (defaults to 10s, can be changed in the TwitterClient).
//
// * `Response` when the received response does not have a 2xx status code.
//   Most responses include additional error information that can be parsed
//   manually from the response's body.
//
// * Other unexpected errors in unlikely events (for example when parsing
//   the response).
```
