### ISSUE TITLE
always getting timeoutexception

### ISSUE THREAD

**Issue by Fnalsk** [robertodoering/twitter_api#19]
I can't seem to get this package to work. It always gives a timeoutexception, no matter what function I try to call with it. I've included an example below.

```
TwitterApi(
  client: TwitterClient(
    consumerKey: twitterApiKey, // From twitter developer console
    consumerSecret: twitterApiSecretKey, // From twitter developer console
    token: (await secureStorage.read(key: '$twitterAuthTokenKey-${firebaseAuthInstance.currentUser!.uid}'))!, // The token returned after logging into twitter via a user account
    secret: (await secureStorage.read(key: '$twitterAuthTokenSecretKey-${firebaseAuthInstance.currentUser!.uid}'))!, // The token secret returned after logging into twitter via a user account
  )
);

try {
  var a = await twitterApi.tweetService.update(
    status: 'Hello world!',
  );
  logger.d(a);
} catch (e) {
  logger.e(e);
}
```

**Comment by robertodoering** [comment]
Requests time out after 10 seconds by default, you can try to give the `TwitterClient` a longer timeout (by setting the `defaultTimeout` in its constructor) if that's not enough time.

What platform are you using this on?
Do other work as expected? You can try using the http package to make any request.

**Comment by Fnalsk** [comment]
This is on a physical android device (s10, android 11).

The device itself can make requests in other parts of the app just fine. A longer timeout doesn't seem to be the solution; just making a tweet saying "hello world" shouldn't take longer than 10s.

**Comment by Fnalsk** [comment]
Not sure what changed over the last few days, but it seems this is no longer occurring on the latest version of this package. Closing.
