### ISSUE TITLE
Media entity indices

### ISSUE THREAD

**Issue by matiasosuna** [robertodoering/twitter_api#20]
I'm trying to display tweets in my app and I've noticed that the array corresponding to indices is mapped as 'indicies' instead of 'indices' and the Tweet object is returning null for that indices field

```
  /// An array of integers indicating the offsets within the Tweet text where
  /// the URL begins and ends. The first integer represents the location of the
  /// first character of the URL in the Tweet text. The second integer
  /// represents the location of the first non-URL character occurring after the
  /// URL (or the end of the string if the URL is the last part of the Tweet
  /// text).
  List<int>? indicies;
```

> from lib/api/media/data/media.dart

I've checked the Twitter API documentation and it shows that the Media object has an 'indices' field: 

https://developer.twitter.com/en/docs/twitter-api/enterprise/data-dictionary/native-enriched-objects/entities#entitiesobject

**Comment by robertodoering** [comment]
The the response does indeed include an `indices` and wasn't parsed due to that typo.
Thanks for reporting the issue, I just published 0.5.6 that includes the fix.
