### ISSUE TITLE
Is @notImplemented attached to the implemented method?

### ISSUE THREAD

**Issue by myConsciousness** [robertodoering/twitter_api#21]
Hi amazing developers,

Recently I started using this library. While using various functions, I noticed that methods that appear to be already implemented are annotated with `notImplemented` annotations. Is this because you are still being implemented?

<img width="592" alt="スクリーンショット 2022-04-12 17 11 47" src="https://user-images.githubusercontent.com/13072231/162913782-19174e44-d46f-47ef-bd75-4b7a6f05d8ce.png">

Thank you.

**Comment by robertodoering** [comment]
Hey @myConsciousness,
thank you!

`followersList` is already implemented - so this annotation can be removed.

I just removed it here: 06d2154
