### ISSUE TITLE
Unimplemented methods

### ISSUE THREAD

**Issue by myConsciousness** [robertodoering/twitter_api#22]
Hi amazing developers,

Thanks for fixing at #21 :)

This is a different issue, but some methods are provided in an unimplemented state. 
Is this because Twitter API limitations make it difficult to implement?

Thank you.

**Comment by robertodoering** [comment]
Hey,
The annotation `@notImplemented` is just for methods that aren't yet implemented, but that doesn't mean it's difficult to implement.

If there is a Twitter API endpoint that you want to use that is `@notImplemented`, you can still use the client to make the request.
(See https://github.com/robertodoering/twitter_api/wiki/Making-a-custom-request-to-the-Twitter-API)
