### ISSUE TITLE
TimeoutException after 0:00:10.000000: Future not completed

### ISSUE THREAD

**Issue by SJT-TONG** [robertodoering/twitter_api#23]
When I use the aqueduct (conduct) back-end framework and dart to write the back-end, I simulate the twitter API request to create a tweet. I have successfully created it in the flutter project on the Android side. However, if I test with this framework, there is only one Mian function in the main program entry and directly call the test method. In this way, an error message appears after running. It is useless to modify the timeout for a long time, This code is the same as that in fluent

TimeoutException after 0:00:10.000000: Future not completed

![image](https://user-images.githubusercontent.com/90231125/166152933-09cf1aea-81a7-4b49-88ea-c17b88da3110.png)
final twitterApi = TwitterApi(
  client: TwitterClient(
      consumerKey: '',   //There are no errors in the parameters
      consumerSecret: '',
      token: '',
      secret: '',
      defaultTimeout: const Duration(minutes: 2)),
);
Future<void> test() async {
  try {
    // Update your status (tweet)
    await twitterApi.tweetService
        .update(
          status: 'Hello world!',     //The modified text information cannot be repeated in a short time
        )
        .whenComplete(() => print("success"));
  } catch (error) {
    print('error while requesting home timeline: $error');
  }
}
//Only these packages and versions
dependencies:
  # aqueduct: 3.3.0+1
  random_string:
  crypto: ^3.0.2
  dart_twitter_api: ^0.5.6+1
  http: 0.13.4
  conduit: ^3.1.2

**Comment by robertodoering** [comment]
This issue seems unrelated to this library
