### ISSUE TITLE
 Internal Server 500 "message":"Could not authenticate you."

### ISSUE THREAD

**Issue by rrawann** [robertodoering/twitter_api#30]
Hello 
I use passport-twitter with NestJs when signUp with twitter and I have my consumerKey and consumerSecret , but i got  Internal Server 500 "message":"Could not authenticate you." how can fix it?

**Comment by robertodoering** [comment]
If you have an issue with passport-twitter, open it in the proper repository https://github.com/jaredhanson/passport-twitter
