### ISSUE TITLE
Sometimes tweets wont get tweeted

### ISSUE THREAD

**Issue by robertodoering** [robertodoering/twitter_api#4]
```
When is use the API to update (create) a tweet, it will sometimes get an error response:
Status code:401
{"errors":[{"code":32,"message":"Could not authenticate you."}]},
reason: Authorization Required

But only sometimes, so often it does not occur
```

From: https://github.com/robertodoering/harpy/issues/207 (thanks @nikolajjsj)

**Comment by nikolajjsj** [comment]
Often it occurs when i attach a media id, and write a status with more/around 100 characters.. I've tried to figure this out but cant get it to work.. If i try to attach a media id and only write one/few words it update succesfully

**Comment by nikolajjsj** [comment]
I have some more information now!
The problem occurs when I have a "!", in the tweet text.. This occurs both when a media has been attached or not.

**Comment by robertodoering** [comment]
Thanks, with that I can reproduce the issue.
I will investigate what causes the problem and keep you updated

**Comment by nikolajjsj** [comment]
> Thanks, with that I can reproduce the issue.
> I will investigate what causes the problem and keep you updated

Awesome, let me know if you need help/more information!
Just to let you know, i really like the work you've done on this library! Great simple and readable code 👍

**Comment by robertodoering** [comment]
Thanks a bunch!
It looks like the query params get encoded correctly in the request. Maybe the oauth1 library is not calculating the signature correctly. I'll check it out further when I have the time

**Comment by robertodoering** [comment]
Turns out `!*'()` didn't get encoded correctly in the oauth1 package.
I fixed this here https://github.com/nbspou/dart-oauth1/pull/10. 

If you don't want to wait for the fix to get published, you can use
```yaml
dart_twitter_api: 
    git: https://github.com/robertodoering/twitter_api
```
as the dependency in your `pubspec.yaml`.

Plese let me know whether this worked for you when you get a chance to test it!

**Comment by nikolajjsj** [comment]
It seems to work, I'll let you know if i run into problems at a later time
